# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
   branches: [ master ]
  schedule:
   - cron: "0 14 * * *"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
    - run: npm ci
    # - run: npm run build
    - run: npm run start
      env: 
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  
    

